# -----------------------------------------------------------------------
#
#   Configuration Makefile for RH
#
#   Edit the variables below to reflect your compilers and environment.
#
# -----------------------------------------------------------------------

CC       = gcc-9
# CFLAGS   = -Og -DHAVE_F90 -Wformat -g -fPIC -std=c11 -DCMO_NO_PROF
# CFLAGS   = -O3 -DHAVE_F90 -Wformat -g -fPIC -std=c11 -DCMO_NO_PROF -march=native -mtune=native -funroll-loops
CFLAGS   = -O0 -DHAVE_F90 -Wformat -g -fPIC -std=c11 -march=native -mtune=native -funroll-loops

F90C     = gfortran
F90FLAGS = -O3 -fPIC

LD       = gcc-9
# LDFLAGS  = -L../ -lrpmalloc -lrpmallocwrap 
 LDFLAGS  =

AR       = ar
ARFLAGS  = rs
RANLIB   = ranlib

HDF5_DIR = /usr/local

# The OS variable should have the operative system name
# If the command below is unavailable, please edit manually
OS = $(shell uname -s)
