# -----------------------------------------------------------------------
#
#   Configuration Makefile for RH
#
#   Edit the variables below to reflect your compilers and environment.
#
# -----------------------------------------------------------------------

CC       = gcc8
CFLAGS   = -O2 -DHAVE_F90 -Wformat -g

F90C     = gfortran8
F90FLAGS = -O2

LD       = gcc8
LDFLAGS  =

AR       = ar
ARFLAGS  = rs
RANLIB   = ranlib

HDF5_DIR = /usr/local

# The OS variable should have the operative system name
# If the command below is unavailable, please edit manually
OS = $(shell uname -s)
